[package]
name = "retrocade-dmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.1.0"
game-loop = "0.10.2"
rustils = "0.1.23"
winit = "0.28.3"
