[package]
name = "cade-dmg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustils = "0.1.23"
sdl2 = "0.35.2"